### ISSUE TITLE
Set up Database + API

### ISSUE THREAD

**Issue by huthuthiddeli** [huthuthiddeli/SYP_PROJEKT_23-24_Maier#16]
# As a client, I want to save data from the Mbot to the database, so that the data can be used lateron.

## Acceptance Criteria:
- Functional MongoDB database with no security breaches.
- Functional API for communication between RestApi and database.
- Check for improvements

## Tasks
- [ ] Set up MongoDB database with authentication.
- [ ] API script with no security leaks and the best possible Module.
- [ ] Implement security mechanisms for incoming data.
